[package]
name = "cheese-paper"
version = "0.1.0"
edition = "2024"

[dependencies]
# file components
serde = "1.0"
toml = "0.8"
toml_edit = "0.22.27"
regex = "1.11.1"
uuid = { version = "1.17.0", features = ["v4"] }
clap = { version = "4.5.40", features = ["derive"] }
log = "0.4.27"

# ui
egui = "0.31"
eframe = { version = "0.31", default-features = false, features = [
    "accesskit",     # Make egui compatible with screen readers. NOTE: adds a lot of dependencies.
    "default_fonts", # Embed the default egui fonts.
    "glow",          # Use the glow rendering backend. Alternative: "wgpu".
    "persistence",   # Enable restoring app state when restarting the app.
    "wayland",       # To support Linux (and CI)
    "x11",           # To support older Linux distributions (restores one of the default features)
] }

env_logger = { version = "0.10", default-features = false, features = [
    "auto-color",
    "humantime",
] }
