name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            name: linux-x86_64
            archive_name: cheese-paper
          - os: windows-latest
            name: windows.exe
            archive_name: cheese-paper.exe
          - os: macos-latest
            name: macos
            archive_name: cheese-paper

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Run test_tracker_move_from_moved_folder
      env:
        RUST_BACKTRACE: '1'
      run: cargo test --release test_tracker_move_from_moved_folder
    - name: Run test_tracker_move_from_moved_folder 2
      env:
        RUST_BACKTRACE: '1'
      run: cargo test --release test_tracker_move_from_moved_folder
    - name: Run test_tracker_move_from_moved_folder 3
      env:
        RUST_BACKTRACE: '1'
      run: cargo test --release test_tracker_move_from_moved_folder
    - name: Run test_tracker_new_file_index 1
      env:
        RUST_BACKTRACE: '1'
      run: cargo test --release test_tracker_new_file_index
    - name: Run test_tracker_new_file_index 2
      env:
        RUST_BACKTRACE: '1'
      run: cargo test --release test_tracker_new_file_index
    - name: Run test_tracker_new_file_index 3
      env:
        RUST_BACKTRACE: '1'
      run: cargo test --release test_tracker_new_file_index
    - name: Run test_tracker_orphaned_file_objects 1
      env:
        RUST_BACKTRACE: '1'
      run: cargo test --release test_tracker_orphaned_file_objects
    - name: Run test_tracker_orphaned_file_objects 2
      env:
        RUST_BACKTRACE: '1'
      run: cargo test --release test_tracker_orphaned_file_objects
    - name: Run test_tracker_orphaned_file_objects 3
      env:
        RUST_BACKTRACE: '1'
      run: cargo test --release test_tracker_orphaned_file_objects
    - name: Run test_tracker_move_and_modify_folder 1
      env:
        RUST_BACKTRACE: '1'
      run: cargo test --release test_tracker_move_and_modify_folder
    - name: Run test_tracker_move_and_modify_folder 2
      env:
        RUST_BACKTRACE: '1'
      run: cargo test --release test_tracker_move_and_modify_folder
    - name: Run test_tracker_move_and_modify_folder 3
      env:
        RUST_BACKTRACE: '1'
      run: cargo test --release test_tracker_move_and_modify_folder
    - name: Run test_tracker_move_into_moved_folder 1
      env:
        RUST_BACKTRACE: '1'
      run: cargo test --release test_tracker_move_into_moved_folder
    - name: Run test_tracker_move_into_moved_folder 2
      env:
        RUST_BACKTRACE: '1'
      run: cargo test --release test_tracker_move_into_moved_folder
    - name: Run test_tracker_move_into_moved_folder 3
      env:
        RUST_BACKTRACE: '1'
      run: cargo test --release test_tracker_move_into_moved_folder
    - name: Run tests all
      env:
        RUST_BACKTRACE: '1'
      run: cargo test --release
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: cheese-paper-${{ matrix.name }}
        path: target/release/${{ matrix.archive_name }}
